# name: Python CD

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.11"

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#       - name: Run pipeline
#         run: |
#           python src/pipeline.py

#       - name: Verify output
#         run: |
#           test -f output/customers_processed.csv

#       - name: Deployment successful
#         run: |
#           echo "Customer pipeline deployed successfully!"

name: Python CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t customer-data-pipeline:latest .

      - name: Run Docker container
        run: |
          docker run --name customer-pipeline customer-data-pipeline:latest

      - name: Verify output
        run: |
          docker cp customer-pipeline:/app/output/customers_processed.csv ./customers_processed.csv
          test -f customers_processed.csv

      - name: Deployment successful
        run: |
          echo "Dockerized customer pipeline deployed successfully!"